version: '2'

services:

  hay:
    build: .
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AZURE_ACCOUNT_NAME: ${AZURE_ACCOUNT_NAME}
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      AZURE_CONTAINER: ${AZURE_CONTAINER}
      AZURE_FILE_SHARE: ${AZURE_FILE_SHARE}
      CONTENT_STORE_ENDPOINT: ${CONTENT_STORE_ENDPOINT}
      ADOBE_TRACKING_URL: ${ADOBE_TRACKING_URL}
      CMS_ENV: ${CMS_ENV}
      PUBLIC_URL: /oneyou/public
    ports:
      - "8000:8000"

  initializer:
    build: .
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AZURE_ACCOUNT_NAME: ${AZURE_ACCOUNT_NAME}
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      AZURE_CONTAINER: ${AZURE_CONTAINER}
      AZURE_FILE_SHARE: ${AZURE_FILE_SHARE}
      CONTENT_STORE_ENDPOINT: ${CONTENT_STORE_ENDPOINT}
      ADOBE_TRACKING_URL: ${ADOBE_TRACKING_URL}
      CMS_ENV: ${CMS_ENV}
      PUBLIC_URL: /oneyou/public
    command: bash ./initialize.sh
